### PR TITLE
added the VoxelVolume app from https://github.com/sorenchr2011/voxvol…

### PR DESCRIPTION
**Pull request by muschellij2**
I added the VoxelVolume App ( Voxel Volume Calculation and Discretization of ROI in Osirix) from https://github.com/sorenchr2011/voxvol, but I think @sorenchr2011 should approve.

### CODE REVIEW

**Comment by sorenchr2011** [comment]
I'd approve but I don't think I'm authorized!

Thanks!
Soren

**Comment by fvpolpeta** [comment]
Hi -

The approval you refer to is about merging the pull request or copyrights over the plugin?

I can accept the pull request and work with you on the migration of it to Horos. 

Thanks

Fauze

**Comment by sorenchr2011** [comment]
That would be great.
Thanks!

Let me know if to make any changes.

Soren

**Comment by fvpolpeta** [comment]
Sure. 

But back to my question, do you own or have copyrights over this plugin? Can we set a LGPL license to it?

Fauze

**Comment by muschellij2** [comment]
@sorenchr2011 is the creator and therefore owns it.  @sorenchr2011 - is LGPL license OK with you?

**Comment by sorenchr2011** [comment]
Yes LGPL is fine.

Thanks,
Soren

**Comment by fvpolpeta** [comment]
The migration of this plugin to Horos will take place next week.

I will let you know if some support is needed.

Thanks for your collaboration.

Fauze

**Pull request merged**
